# Generated by Django 2.0.7 on 2019-04-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_currentuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('userid', models.CharField(db_column='txt', max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'History',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='currentuser',
            table='CurrentUser',
        ),
    ]
