# Generated by Django 2.0.7 on 2019-04-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190423_0549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'managed': True},
        ),
    ]
