# Generated by Django 2.0.7 on 2019-04-23 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190423_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='auto_increment_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='itemid',
            field=models.ForeignKey(db_column='ItemID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='userid',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Customer'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together={('userid', 'itemid')},
        ),
    ]
