# Generated by Django 2.0.7 on 2019-04-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190423_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='auto_increment_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
