# Generated by Django 2.0.7 on 2019-04-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190423_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='auto_increment_id',
            field=models.IntegerField(db_column='auto_increment_id', primary_key=True, serialize=False),
        ),
    ]
