# Generated by Django 2.0.7 on 2019-04-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20190426_0323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'managed': False},
        ),
    ]
